### ISSUE TITLE
Set up ActiveAdmin

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#10]
[Link to ActiveAdmin](https://github.com/activeadmin/activeadmin)

**Comment by isuriupeksha** [comment]
I don't think we need to use ActiveAdmin for this project. ActiveAdmin doesn't support responsive layouts for mobile. Also it use `<table>` HTML structure which is not fit to mobile view. 

Just check Google material design cards. http://www.google.com/design/spec/components/cards.html

**Comment by wonook** [comment]
I'm not doing this for mobile. This is a tool that enables an administrator to manage elements and objects of particular models, since it wouldn't be an easy job for non-developers to have access to the rails console and manipulate objects.

**Comment by isuriupeksha** [comment]
Ok, it is good for the development environment only.

**Comment by rosariorobinson** [comment]
@abelards any input here? 

Developing for long-term is good practice. We're not considering mobile right now, but that is the thinking for those out in the field and want to take a quick photo and uploading to the application right from the phone. PC volunteers are more apt to have their phone with them than their laptops, particularly in rural area.

Good discussion to have.

**Comment by abelards** [comment]
I actually don't see a conflict there, only two nice improvements complementing each other.

It is fully possible to have an admin backend AND a cool view for users.
@wonook is doing the first, @isuriupeksha is doing the second.
Their work will not conflict with each other, especially if @wonook sets up different routes.

---

ActiveAdmin will lower cost for new features, and lower the maintenance cost in the long run.
This is a great move and also why I supported his GSoC application.
Easy to code, easy to maintain: this is the difference between an app that works and an app that don't.

@isuriupeksha will improve the design. She will work on whatever views she likes, not the backend.
This is a great addition and the quality of the mockups, and why I supported her application.
Easy to use, easy to understand: that is the difference between an app with no users and an app that people will actually use.

I will never choose between the two because we need both, and it looks like we got the right team for that, if we communicate enough... and we all know THAT challenge is much harder than just code :)

---

A concrete example: test.com/admin/resource will be "efficient for power users, but ugly" and test.com/resources will be "beautiful, and easy to use for normal people". This is the route setup I'm talking about. I seldom do this at work but if they have problem setting this up I'll have a look.

Also I must be very humble about design because I am lousy at this. Whatever the project, I know I can do a backend, my frontends work but are ugly: if someone gives me a frontend people will love, I know we can achieve great things!

Cheers,
