### ISSUE TITLE
config/database.yml.example should be added to .gitignore

### ISSUE THREAD

**Issue by paavininanda** [systers/language-translation#239]
Since this file should be deleted after cloning the project, this file should be added to .gitignore

**Comment by adityathiru** [comment]
That's not a problem. It's meant as a reference for new comers to get an idea.

On 31-Jan-2018 22:12, Paavini Nanda <notifications@github.com> wrote:

Since this file should be deleted after cloning the project, this file should be added to .gitignore

**Comment by paavininanda** [comment]
Yes, but i am personally getting this problem every time, I am not able to do git stash because of this. I think it would be a better to add this to .gitignore instead.

**Comment by adityathiru** [comment]
You need to create a seperate database.yml file. That is already there in gitignore I think. I never seemed to have the issue though !

On 31-Jan-2018 22:18, Paavini Nanda <notifications@github.com> wrote:

Yes, but i am personally getting this problem every time, I am not able to do git stash because of this. I think it would be a better to add this to .gitignore instead.

**Comment by prachi1210** [comment]
Yes, a database.yml file already exists in the .gitignore. The point of having .example files is that you can rename them and leave .example files untouched

**Comment by paavininanda** [comment]
Since point 3 in README says rename config/database.yml.example to config/database.yml, i renamed the file. So when i do git status I see **deleted: config/database.yml.example**
Or we can change that point to create a new file.

**Comment by adityathiru** [comment]
The best way to avoid that is to duplicate that file and rename one of them to database.yml. That way you shouldn't face any errors. Probably that's what should've been written in the readme. 😅

On 31-Jan-2018 22:23, Paavini Nanda <notifications@github.com> wrote:

Since point 3 in README says rename config/database.yml.example to config/database.yml, i renamed the file. So when i do git status I see deleted: config/database.yml.example
Or we can change that point to create a new file.
