### ISSUE TITLE
`username` input filed is requited?

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#25]
Currently user can only login using username. Do we really want to use `username`? Because we use `email`, ` first_name` and `last_name` for the user identification. So we can use `email` and `password` input field to login to the system.  What is the your suggestion?

**Comment by isuriupeksha** [comment]
I am integrating user invitation feature into the members management section. We can send a invitation by using `email` only. But when user accept the invitation, we need to provide a additional input field `username` while user enter password confirmation. I think, it is a additional input field on the accept invitation form.

**Comment by SaumyaGurtu** [comment]
@isuriupeksha : 
1. I'll first tell you what was the reason behind taking 'username' for login. Actually, "Look, feel, functionality & design behaviour should be in sync with other Peace Corps projects." is what we thought. So the UI design was prepared by Vaibhavi Desai last year who worked for Malaria Prevention Application and we used the same forms and application behaviour. For this reason I made changes in default files created by devise because it creates a sign in with email and password by default. 
But, you are right that email id is unique and we do not need any username for that.

2. Since, internet is not available most of the times for local users,i.e., contributors, should we go for with "email invitation only" ? Or, a simple accept invitation with email confirmation(user can confirm his/her email later). 

@rosariorobinson : please have a look at these and guide us on what needs to be done.

**Comment by wonook** [comment]
We've had this discussion on slack, but I think having username has more +s than -s. It makes signing in easier, by lifting the need of writing the entire email address every time signing in, and also it lets people find each other on the application easier (when we want to add people as members, etc). I'm sure there are other reasons as well, but I don't think there's a need for getting rid of people's username.

**Comment by wonook** [comment]
I guess this one's solved. We'll leave the username and the corresponding migrations.
