### ISSUE TITLE
Login at organization level (this could potentially be something other organizations can use)

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#30]
This well explained by @SaumyaGurtu (copied from #slack)

------------
Organisation is basically a country level. Forex micronesia this country might have many sites which peace corps people technically call them as posts. Volunteers are allotted specific posts. Each post have local people who know the target language , for ex chuukese , very well.

Similar to micronesia there are many countries where peace corps work so they want the login to application by organization. So no person from other organisation can access or edit records of the first.

You may have a super-admin for all organizations and admins for each organization
Because for each organization we have to handle records of languages, articles, pictures, volunteers, contributors, sites and login approvals of requests .

So volunteer of one organization cant ask for login request approval from other organization admin. 

------------

Following things need to fix.

1. Add supper-admin (Supper-Admin can see all Users)
2. Create an organization model 
3. Associate with `User` and `Organization` models  + permission
4. Introduce a one authorization level for User + Organization permission.
5. Group by Organization. (One organization can only see their members)

Please comment any concerns. 

I will provide design comps for Organization + User management by two days. It is easy to understand everyone, what is the end output.

**Comment by wonook** [comment]
I think it would be nice if we could have a list of 'organizations' at the main page, for the users to choose their organization from the list and do whatever they want to do in that organization. If the user is signed in (by enabling automatic sign-in or remember me functionality), then the user can be automatically redirected to the organization that they belong to.
Still, I have some concerns regarding the users who are members of multiple organizations and their roles. I'm currently not 100% familiar with the CanCan gem, but is there a way for users to have different roles for different organizations? According to my memory, I think I've been trying to make that happen in some other project of mine and found a different solution for it because I couldn't do it.

**Comment by wonook** [comment]
I'll delete the `role` column from the `user` model and use the `Rolify` gem to attach 'roles' to each 'users' on the corresponding 'organizations'.
`Rolify` works quite gracefully with `CanCanCan`, so it wouldn't be a problem.
This implementation closes #32.

**Comment by wonook** [comment]
About the 'SuperAdmin' I'll create another model called `AdminUser`, which is automatically generated by the `ActiveAdmin` gem. The users that belong to `AdminUser` model will be able to have full access to all materials through `ActiveAdmin` interface. This was the part that I was having trouble with, trying to fit ActiveAdmin into this application (#10), but I guess this plan will get everything sorted out quite nicely.

**Comment by isuriupeksha** [comment]
I don't think, we really need `ActiveAdmin` gem for this application. Since we need one `supperAdmin` as mentioned by @SaumyaGurtu, all record can be managed by `supperAdmin` in `User` model.

**Comment by wonook** [comment]
Do you know what the gem does?
I think it will be a neat solution for organizing the application for a super-administrator. Without it, we'll have to come up with all the solutions for displaying and managing information for that single person. Let's not reinvent the wheel.

**Comment by isuriupeksha** [comment]
Yes, this gem also can manage all the record updating, deleting or adding records all models. We do the same thing now. `Admin` user can manage all photos, and other records edits and delete. Once we introduce `super-admin`, it will allows to manage all records by changing authorization using cancan. 

By adding this gem, it is for me just like `phpmyadmin` integration.

**Comment by isuriupeksha** [comment]
What Admin panel is about the reports. 
Something like this, 
1. what is the post frequent. 
2. In with organization which created posts amounts.
3. Activity log
etc...

**Comment by wonook** [comment]
I'll consider about it a bit. First let's focus on the 'organization' stuff. I think I'll be able to do that without creating another role for the users by using `Rolify`. I'll be able to set an `admin` for each of the organizations as well of for the entire application.

**Comment by isuriupeksha** [comment]
@wonook  Don't really understand I am interrupting to `ActiveAdmin` feature implementation. But that was my understanding how we can implementing Admin. 

When I think about Admin section what should be, it just like charts and reports. 

* What are the frequently used articles (by chart)
* Sending time etc..

**Comment by wonook** [comment]
Oh, I think with the help of `Google Analytics` those charts will be organized pretty nicely. No worries about that I guess.
The reason why I think `ActiveAdmin` is great, is because it enables non-developer users to use functionalities that `$ rails console` provides us without the barrier to learn ActiveRecords. It enables administrators to fix and edit things like `categories`, and other things that may be implemented in the future. There may be some things that we don't want to have an extra view for, since it would get too crowded once we have a view for each and every model in the application. I'm just trying to provide access to the `rails console` for non-developer admins.

**Comment by wonook** [comment]
I'm waiting for an answer on #35

**Comment by rosariorobinson** [comment]
Answer to #35 about orgs. Exactly what the title suggest, this is potential app other orgs can use.

**Comment by wonook** [comment]
A note for myself:
- [ ] Creating organization model
- [ ] Attaching organization to each post
- [ ] Attaching organization to each user
- [ ] Changing the MVC accordingly
- [ ] Hiding materials that are irrelevant to the user's organization
- [ ] Restructuring roles

**Comment by wonook** [comment]
A note for myself:
- [x] Creating organization model
- [x] Attaching organization to each post
- [x] Attaching organization to each user
- [x] Changing the MVC accordingly
- [ ] Hiding materials that are irrelevant to the user's organization
- [ ] Restructuring roles
