### ISSUE TITLE
Commenting & keeping notes for a particular article - new feature

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#38]
Team members may want to  comments or add notes to an article (photo) while publish the article.
Once members add comment or note, it will receive as message via email to the inbox. 

If a user wants to comment on an article, he/she needs to log in by clicking the direct URL mentioned in the email. This feature will help to improve the content of the translations.

Welcome your suggestions!

**Comment by wonook** [comment]
particur --> particular

**Comment by abelards** [comment]
I don't really get who gets what mail, could you elaborate on that?
I see 3 main kinds of audience: "author", "last editor", "whoever is in the discussion" (or "admins" or...)

If you do this you'll potentially generate a tremendous amount of emails: you then have to implement a way of "subscribing / unsubscribing" to conversations.

Apart from that it's an interesting feature. My customer says:
"we can do everything given unlimited time and money", which Systers doesn't have,
so though I like the idea I will ask @rosariorobinson to prioritize this:
"vital" or "nice-to-have", "ASAP" or "later" ?

Cheers!

**Comment by rosariorobinson** [comment]
Let's keep in mind this project is for Peace Corps volunteers trying to learn a language. How they are learning are through phonetic sounds from native speakers because there is NO written language at this point. 

Native speakers are also learning English so how would they know what spell checking is when they are typing. 

The ideas are great, but keep your users in mind during development. It's easy to get caught up in the development and forget the purpose of the application.

The users are:
1. Administrators (systers, peace corps HQ)
2. Peace Corps Volunteers who want to use app as a tool for learning native language and teaching English (both ways)
3. Guests who are native speakers who may not know English

**Comment by wonook** [comment]
@rosariorobinson 
I think there are also `contributors` who have contributed to the application by posting an article!
